version: "3.8"

services:

  selenium-hub:
    image: selenium/hub:4.27.0
    restart: unless-stopped
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      - SE_GRID_MAX_SESSION=4
    mem_limit: 512m

  chrome-node:
    image: selenium/node-chrome:4.27.0
    restart: unless-stopped
    depends_on:
      - selenium-hub
    shm_size: "1gb"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=300
    mem_limit: 700m

  lead-gen-api:
    image: ${ECR_IMAGE}
    restart: unless-stopped
    ports:
      - "80:7860"
    depends_on:
      - selenium-hub
    environment:
      - S3_BUCKET_NAME=lead-gen-data-vishal
      - AWS_REGION=ap-south-1
      - SELENIUM_HUB_URL=http://selenium-hub:4444
      - SELENIUM_DRIVERS_COUNT=6
      - GOOGLE_API_KEY=AIzaSyBNhQK0iONS8JYDrHSPPpbNNpwegaSZgHY
    mem_limit: 2500m
